name: Android CI/CD - Build & Release APK

on:
  push:
    branches:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | tr -d '\n ' | base64 --decode > app/noteapp-release.keystore

      - name: Build APK Release
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PATH: noteapp-release.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Cleanup Keystore
        run: rm app/noteapp-release.keystore

      - name: Rename APK
        run: |
          RAW_REF="${{ github.ref_name }}"
          
          VERSION_PART=$(echo $RAW_REF | awk -F'/' '{print $NF}')
          
          RELEASE_TITLE=$(echo $SAFE_TAG | sed 's/-/ /g')
          
          SAFE_TAG=$(echo $VERSION_PART | sed -E 's/([0-9])-([0-9])/\1.\2/g; s/([0-9])-([0-9])/\1.\2/g')

          FILE_NAME="v-$(echo $VERSION_PART)"

          echo "SAFE_TAG=$SAFE_TAG" >> $GITHUB_ENV
          echo "RELEASE_TITLE=$RELEASE_TITLE" >> $GITHUB_ENV
          echo "SAFE_FILENAME=karna-notes-$FILE_NAME.apk" >> $GITHUB_ENV
          
          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/karna-notes-$FILE_NAME.apk

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.SAFE_TAG }}
          name: ${{ env.RELEASE_TITLE }}
          body: |
            # **Karna Notes** - ${{ env.RELEASE_TITLE }}
            
            **Download APK**: [${{ env.SAFE_FILENAME }}](https://github.com/${{ github.repository }}/releases/download/${{ env.SAFE_TAG }}/${{ env.SAFE_FILENAME }})
            
            **Full Changelog**: https://github.com/${{ github.repository }}/commits/${{ github.ref_name }}
          draft: false
          prerelease: false
          files: app/build/outputs/apk/release/${{ env.SAFE_FILENAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
